version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: gestao_vet_email
    environment:
      POSTGRES_DB: email_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    volumes:
      - /var/to/local/data:/var/lib/postgresql/data